services:
  control-node:
    image: ubuntu:22.04
    container_name: control-node
    tty: true
    volumes:
      - .:/root/ansible # mount local drive
    networks:
      - ansible-net

  web01:
    image:   rastasheep/ubuntu-sshd
    container_name: web01
    networks:
      - ansible-net

  web02:
    image:   rastasheep/ubuntu-sshd
    container_name: web02
    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridge
